name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
resources:
  repositories:
    - repository: tox
      type: github
      endpoint: mitre
      name: tox-dev/azure-pipelines-template
      ref: refs/tags/0.2

trigger:
  batch: true

jobs:
  - template: run-tox-env.yml@tox
    parameters:
      tox_version: "tox"
      jobs:
        style:
          image: [ubuntu-20.04]
        py37:
          image: [ubuntu-20.04, macOs]
        py38:
          image: [ubuntu-20.04, macOs]
        py39:
          image: [ubuntu-20.04, macOs]
      coverage:
        with_toxenv: "coverage"
        for_envs: [py39, py38, py37]
